// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEbdpkgk7OnR4qxT3N-tpINqo2emX7tdU',
    appId: '1:281429853977:web:166e2c7739bd496b37a788',
    messagingSenderId: '281429853977',
    projectId: 'cb-estimation-system',
    authDomain: 'cb-estimation-system.firebaseapp.com',
    storageBucket: 'cb-estimation-system.appspot.com',
    measurementId: 'G-YXWGM5HJSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFFLQ1CsVtvgCC8DEZgPB2gx1M0Yq3Aow',
    appId: '1:281429853977:android:7a6698d045f7026437a788',
    messagingSenderId: '281429853977',
    projectId: 'cb-estimation-system',
    storageBucket: 'cb-estimation-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5REPmZqCJQl_E_dB5SBNTfVcH5GE8WYk',
    appId: '1:281429853977:ios:a87c1c87ab1c60d737a788',
    messagingSenderId: '281429853977',
    projectId: 'cb-estimation-system',
    storageBucket: 'cb-estimation-system.appspot.com',
    iosClientId: '281429853977-euvlfl9nj8mek411t6nhusdjto2s23fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.constructionBudgetEstimationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5REPmZqCJQl_E_dB5SBNTfVcH5GE8WYk',
    appId: '1:281429853977:ios:a87c1c87ab1c60d737a788',
    messagingSenderId: '281429853977',
    projectId: 'cb-estimation-system',
    storageBucket: 'cb-estimation-system.appspot.com',
    iosClientId: '281429853977-euvlfl9nj8mek411t6nhusdjto2s23fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.constructionBudgetEstimationSystem',
  );
}
